// <auto-generated />
namespace Pt.DL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class a5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(a5));
        
        string IMigrationMetadata.Id
        {
            get { return "201711281458011_a5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
